sudo: required
services:
  - docker

before_install:
  - docker build -t mohdaf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mohdaf/react-test npm test -- --coverage

after_success:
  - docker build -t mohdaf/multi-client ./client
  - docker build -t mohdaf/multi-nginx ./nginx
  - docker build -t mohdaf/multi-server ./server
  - docker build -t mohdaf/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push mohdaf/multi-client
  - docker push mohdaf/multi-nginx
  - docker push mohdaf/multi-server
  - docker push mohdaf/multi-worker
